# Generated by Django 4.1.7 on 2023-02-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание')),
                ('status', models.CharField(default='new', max_length=200, verbose_name='Статус')),
                ('finish_date', models.DateField(verbose_name='Дата выполнения')),
            ],
        ),
    ]
