# Generated by Django 4.1.7 on 2023-02-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_upd', '0002_task_detail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateField(auto_now=True, verbose_name='Дата выполнения'),
        ),
    ]
