# Generated by Django 4.1.7 on 2023-02-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_upd', '0003_alter_task_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateField(verbose_name='Дата выполнения'),
        ),
    ]
